config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/on_article_created.rb
class OnArticleCreated
  def call(event)
    uid = event.data[:article_id]

    return if Article.where(uid: uid).exists?

    Article.create!(
      uid: uid,
      title: event.data[:title],
      content: event.data[:content],
      author: event.data[:author]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    render
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def create
    cmd = Aggregates::CreateArticle.new(
      create_params.to_h.symbolize_keys.merge(article_id: SecureRandom.uuid)
    )

    command_bus.(cmd)

    redirect_to(
      article_path(Article.find_by_uid(cmd.article_id)),
      notice: 'Article was successfully created.'
    )
  end

  private

  def create_params
    params.require(:article).permit(:author, :title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/index.html.haml
Articles
= link_to "New Article", new_article_path
%table
  %tr
    %td Uid
    %td Title
  - @articles.each do |article|
    %tr
      %td= link_to article.uid, article_path(article)
      %td= article.title

app/views/articles/new.html.haml
= form_for @article do |f|
  %p
    = f.label :author, "Author"
    %br
    = f.text_field :author

  %p
    = f.label :title, "Title"
    %br
    = f.text_field :title

  %p
    = f.label :content, "Content"
    %br
    = f.text_area :content

  = f.submit "Create article"

app/views/articles/show.html.haml
%p
  Author:
  = @article.author
%p
  Title:
  = @article.title
%p
  Content:
  = @article.content

  %br
  = link_to "All articles", articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Res</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>